174,0
T,Flt,-,0
A,Flt,13,Boundary,Domain,Image,Indices,Max_Inds,Lattice,Length,Lex_Order,Lie_Alg,Lie_Func,Object,Preorder,Totally_Ordered
S,Filter,"Returns the filter into the subsets of X. The domain of the filter is generated by D, and the corresponding images are I. The preorder is defined by P, where P(x,y) returns true if x `le' y",0,4,0,0,0,0,0,0,0,41,,0,0,82,,0,0,82,,0,0,-1,,Flt,-38,-38,-38,-38,-38
S,TotallyOrderedFilter,"Returns the totally ordered filter into the subsets of X. The domain of the filter is generated by D, and the corresponding images are I. The preorder is defined by P, where P(x,y) returns true if x `le' y. If P is the lexicographical order set Lex to true",0,4,0,0,0,0,0,0,0,41,,0,0,82,,0,0,82,,0,0,-1,,Flt,-38,-38,-38,-38,-38
S,LowerCentralFilter,Returns the lower central filter for a group G,0,1,0,0,0,0,0,0,0,-27,,Flt,-38,-38,-38,-38,-38
S,pCentralFilter,Returns the p-central filter for a group G,0,2,0,0,0,0,0,0,0,148,,0,0,-27,,Flt,-38,-38,-38,-38,-38
S,pCentralFilter,Returns the p-central filter for a p-group G,0,1,0,0,0,0,0,0,0,129,,Flt,-38,-38,-38,-38,-38
S,JenningsFilter,Returns the Jennings filter for a group G,0,1,0,0,0,0,0,0,0,-27,,Flt,-38,-38,-38,-38,-38
S,Print,Print F,0,1,0,0,1,0,0,0,0,Flt,,-38,-38,-38,-38,-38,-38
S,@,s @ F,1,0,1,82,0,148,2,0,0,0,0,0,0,0,Flt,,0,0,82,,-1,-38,-38,-38,-38,-38
S,@,s @ F,0,2,0,0,0,0,0,0,0,Flt,,0,0,148,,-1,-38,-38,-38,-38,-38
S,eq,F eq G,0,2,0,0,0,0,0,0,0,Flt,,0,0,Flt,,36,-38,-38,-38,-38,-38
